services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app
      - user-manager
      - wallpaper-manager
      - interaction-collector

  web-app:
    build:
      context: ./web-app
      args:
        - VITE_API_BASE_URL=/api
    restart: always

  user-manager:
    build: ./user-manager
    environment:
      - JWT_SECRET=nus-iss-software-engineering-big-data
      - POSTGRES_URL=postgresql://user-manager:3f9876c5d8d29c1c490cdaa119a7d5e3@user-manager-postgres:5432/user-manager
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - user-manager-postgres
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  user-manager-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user-manager
      - POSTGRES_PASSWORD=3f9876c5d8d29c1c490cdaa119a7d5e3
      - POSTGRES_DB=user-manager
    volumes:
      - ./user-manager/database:/docker-entrypoint-initdb.d
      - user-manager-postgres-data:/var/lib/postgresql/data
    restart: always

  wallpaper-manager:
    build: ./wallpaper-manager
    environment:
      - API_KEY=only-i-can-scrape-new-wallpapers
      - POSTGRES_URL=postgresql://wallpaper-manager:b9135ff23d8df60de4a4fa7e7d2f8a92@wallpaper-manager-postgres:5432/wallpaper-manager
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - wallpaper-manager-postgres
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  wallpaper-manager-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=wallpaper-manager
      - POSTGRES_PASSWORD=b9135ff23d8df60de4a4fa7e7d2f8a92
      - POSTGRES_DB=wallpaper-manager
    volumes:
      - ./wallpaper-manager/database:/docker-entrypoint-initdb.d
      - wallpaper-manager-postgres-data:/var/lib/postgresql/data
    restart: always

  interaction-collector:
    build: ./interaction-collector
    environment:
      - POSTGRES_URL=postgresql://interaction-collector:54f48a762ab0867b396cde2d14138d20@interaction-collector-postgres:5432/interaction-collector
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - interaction-collector-postgres
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  interaction-collector-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=interaction-collector
      - POSTGRES_PASSWORD=54f48a762ab0867b396cde2d14138d20
      - POSTGRES_DB=interaction-collector
    volumes:
      - ./interaction-collector/database:/docker-entrypoint-initdb.d
      - interaction-collector-postgres-data:/var/lib/postgresql/data
    restart: always

  kafka-1:
    image: apache/kafka-native
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=CONTROLLER://:9091,DOCKER://:9092
      - KAFKA_ADVERTISED_LISTENERS=DOCKER://kafka-1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
    volumes:
      - kafka-1-data:/var/lib/kafka/data
    restart: always

  kafka-2:
    image: apache/kafka-native
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=CONTROLLER://:9091,DOCKER://:9092
      - KAFKA_ADVERTISED_LISTENERS=DOCKER://kafka-2:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
    volumes:
      - kafka-2-data:/var/lib/kafka/data
    restart: always

  kafka-3:
    image: apache/kafka-native
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=CONTROLLER://:9091,DOCKER://:9092
      - KAFKA_ADVERTISED_LISTENERS=DOCKER://kafka-3:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
    volumes:
      - kafka-3-data:/var/lib/kafka/data
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 9090:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  recommend-postgres:
    build: ./pgvector-docker
    environment:
      - POSTGRES_USER=recommend
      - POSTGRES_PASSWORD=3f9876c5d8d29c1c490cdaa119a7d5e3
      - POSTGRES_DB=recommend
    restart: always

  recommend:
    build: ./recommend
    ports:
      - 7071:7071
    environment:
      - JWT_SECRET=nus-iss-software-engineering-big-data
      - POSTGRES_URL=postgresql://recommend:3f9876c5d8d29c1c490cdaa119a7d5e3@recommend-postgres:5432/recommend
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - recommend-postgres

  wallpaper-vectorizer-1:
    build: ./wallpaper-processor
    container_name: wallpaper-vectorizer-1
    environment:
      - CONSUMER_NAME=consumer-1
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_GROUP_ID=vectorizer-group
      - WALLPAPER_SCRAPED_TOPIC=WallpaperScraped
      - WALLPAPER_VECTORIZED_TOPIC=WallpaperVectorized
      - MODEL_PATH=/app/models/bge_model
    volumes:
      - ./wallpaper-processor/models:/app/models
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  wallpaper-vectorizer-2:
    build: ./wallpaper-processor
    container_name: wallpaper-vectorizer-2
    environment:
      - CONSUMER_NAME=consumer-2
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_GROUP_ID=vectorizer-group
      - WALLPAPER_SCRAPED_TOPIC=WallpaperScraped
      - WALLPAPER_VECTORIZED_TOPIC=WallpaperVectorized
      - MODEL_PATH=/app/models/bge_model
    volumes:
      - ./wallpaper-processor/models:/app/models
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  wallpaper-vectorizer-3:
    build: ./wallpaper-processor
    container_name: wallpaper-vectorizer-3
    environment:
      - CONSUMER_NAME=consumer-3
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_GROUP_ID=vectorizer-group
      - WALLPAPER_SCRAPED_TOPIC=WallpaperScraped
      - WALLPAPER_VECTORIZED_TOPIC=WallpaperVectorized
      - MODEL_PATH=/app/models/bge_model
    volumes:
      - ./wallpaper-processor/models:/app/models
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

volumes:
  user-manager-postgres-data:
  wallpaper-manager-postgres-data:
  interaction-collector-postgres-data:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
